Repository devellop-labs/woocommerce-braspag, pull requests merged in 2025-02, with the labels that each got.

#53 Fix: add static in method class API query
  includes/class-wc-braspag-pagador-api-query.php
Labels: bug

#54 Fix: add static in method class API query
  includes/class-wc-braspag-pagador-api-query.php
Labels: bug

#52 Adiciona integração Verify Card com suporte a CardToken e PaymentToken
  assets/js/braspag-authsop.js
  assets/js/braspag-verifycard.js
  assets/js/braspag.js
  includes/admin/braspag-settings.php
  includes/class-wc-gateway-braspag.php
Labels: enhancement

#56 Feature/add validation velocity
  includes/class-wc-gateway-braspag.php
Labels: enhancement

#57 Feature/add silent order post
  assets/js/braspag-authsop.js
  assets/js/braspag.js
  includes/abstracts/abstract-wc-braspag-payment-gateway.php
  includes/admin/braspag-settings.php
  includes/admin/class-wc-braspag-privacy.php
  includes/class-wc-braspag-customer.php
  includes/class-wc-braspag-helper.php
  includes/class-wc-braspag-logger.php
  includes/class-wc-braspag-oauth-api.php
  includes/class-wc-braspag-order-handler.php
  includes/class-wc-braspag-payment-tokens.php
  includes/class-wc-gateway-braspag.php
  includes/payment-methods/class-wc-gateway-braspag-creditcard-justclick.php
  includes/payment-methods/class-wc-gateway-braspag-creditcard.php
  includes/payment-methods/class-wc-gateway-braspag-debitcard.php
  includes/payment-methods/class-wc-gateway-braspag-pix.php
  languages/woocommerce-braspag.po
  wc-gateway-braspag.php
Labels: enhancement

#59 Feature/add verify card
  assets/js/braspag-authsop.js
  assets/js/braspag-verifycard.js
  assets/js/braspag.js
  includes/admin/braspag-settings.php
  includes/class-wc-gateway-braspag.php
Labels: enhancement

#65 Feature/add extradatacollection
  changelog.txt
  includes/payment-methods/class-wc-gateway-braspag-boleto.php
  includes/payment-methods/class-wc-gateway-braspag-creditcard-justclick.php
  includes/payment-methods/class-wc-gateway-braspag-creditcard.php
  includes/payment-methods/class-wc-gateway-braspag-debitcard.php
  readme.txt
  wc-gateway-braspag.php
Labels: enhancement

#66 Docs version chancelog
  changelog.txt
  readme.txt
  wc-gateway-braspag.php
Labels: documentation

#67 Docs version chancelog
  changelog.txt
  readme.txt
  wc-gateway-braspag.php
Labels: documentation
